### ISSUE TITLE
Suggestions for CUDA version instruction

### ISSUE THREAD

**Issue by zhangysh1995** [DBCobra/CobraHome#3]
Hi,

I found that the CUDA version info is given at CobraVerifier's repo not here. _I think it would be better to also add the version requirement on this page._ Because I have a more latest version and I reinstalled it when I saw the instruction there.

And I didn't find a way to install the exact version `CUDA v10.0.130`, but I successfully build and run up CobraVerifier with `CUDA v10.1` on `Debian 10`.

Hope this will help the later users of this tool ;)

**Comment by zhangysh1995** [comment]
One more thing, because for the older version it is necessary to refer an installation step, it is possible to follow [this ](https://gist.github.com/Mahedi-61/2a2f1579d4271717d421065168ce6a73) gist. Though the gist is for Ubuntu 18.04, but it seems also work on Debian 10 in my case.

**Comment by naizhengtan** [comment]
Hi Yushan, thanks for the information. It will definitely help other users.
I also updated the README with the CUDA version.

**Comment by zhangysh1995** [comment]
Solved and closed.
